services:

  flume:
    build:
      context: ./flume

    container_name: flume-semana1

    volumes:
      - ./data:/data/incoming
      - ./flume-output:/data/output
      - ./flume-state:/data/state

    restart: "no"